In [26]:
from sklearn.model_selection import train_test_split
import pandas as pd 

In [27]:
pd.set_option('display.max_columns', None)  # Show all columns

In [28]:
df_ddos = pd.read_csv("dataset/normal_dataset/Only_DDOS.csv",delimiter=",")
df_ddos

/var/folders/nj/scyrvwln431b58h3d50x1v600000gn/T/ipykernel_3874/3977034436.py:1: DtypeWarning: Columns (8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ddos = pd.read_csv("dataset/normal_dataset/Only_DDOS.csv",delimiter=",")


ts_time          uid_string   id.orig_addr  id.orig_port  \
0        1.545452e+09  CmgfaE2BlYQZWKNgy4  192.168.1.196         17217   
1        1.545452e+09  CdUEGF3LGSzBEIkmZb  192.168.1.196         61635   
2        1.545452e+09  CxLtJA4HoDhofMacqi  192.168.1.196         28115   
3        1.545452e+09   CpDo1ucqUWa1TriGj  192.168.1.196         42776   
4        1.545452e+09  CPUivV3glDIFZfYDK7  192.168.1.196         57665   
...               ...                 ...            ...           ...   
2185297  1.545477e+09  CjYmd14eKgtnCFh1Ye  192.168.1.196         53686   
2185298  1.545477e+09   C2WkTRVpaV4yoRLS1  192.168.1.196         56562   
2185299  1.545477e+09   CVdNobsaAanxpggxf  192.168.1.196         56562   
2185300  1.545477e+09  CRs9Lf4TY3Qr9V0vta  192.168.1.196         56562   
2185301  1.545477e+09  C9idx83TKMLu8dQRU4  192.168.1.196         56562   

          id.resp_haddr  id.resp_pport proto_enum service_string  \
0        209.97.190.136             80        tcp              -   
1        209.97.190.136             80        tcp              -   
2        209.97.190.136             80        tcp              -   
3        209.97.190.136             80        tcp              -   
4        209.97.190.136             80        tcp              -   
...                 ...            ...        ...            ...   
2185297   216.18.168.16            443        tcp            ssl   
2185298   216.18.168.16             80        tcp              -   
2185299   216.18.168.16             80        tcp              -   
2185300   216.18.168.16             80        tcp              -   
2185301   216.18.168.16             80        tcp              -   

        duration_interval orig_bytes_count resp_bytes_count conn_state_string  \
0                2.336936                0                0            RSTOS0   
1                3.356312                0                0            RSTOS0   
2                       -                -                -            RSTOS0   
3                3.973249                0                0            RSTOS0   
4                3.823055                0                0            RSTOS0   
...                   ...              ...              ...               ...   
2185297          4.285068              555           386308                SF   
2185298                 -                -                -                SH   
2185299                 -                -                -                SH   
2185300                 -                -                -                SH   
2185301                 -                -                -                SH   

        local_orig_bool local_resp_bool  missed_bytes_count history_string  \
0                     -               -                   0              I   
1                     -               -                   0              I   
2                     -               -                   0              I   
3                     -               -                   0              I   
4                     -               -                   0              I   
...                 ...             ...                 ...            ...   
2185297               -               -                5792    ShADdtatFfR   
2185298               -               -                   0              F   
2185299               -               -                   0              F   
2185300               -               -                   0              F   
2185301               -               -                   0              F   

         orig_pkts_count  orig_ip_bytes_count  resp_pkts_count  resp_bytes  \
0                      2                   80                0           0   
1                      3                  120                0           0   
2                      1                   40                0           0   
3                      4                  160                0           0   
4       

In [29]:
df_ben = pd.read_csv("dataset/normal_dataset/Only_Benign.csv",delimiter=",")
df_ben

ts_time          uid_string    id.orig_addr  id.orig_port  \
0        1.545403e+09  CDn2pd1rDD1lCMXAia   192.168.1.196         35883   
1        1.545403e+09  C1NKkV3tB4rImzbpDj   192.168.1.196         43531   
2        1.545403e+09   Cxoiu11zgEdj4MX27   192.168.1.196         39189   
3        1.545403e+09  ChlyUB4IKofHtlEFO1   192.168.1.196           123   
4        1.545403e+09  CgEG202REue0at76Je   192.168.1.196           123   
...               ...                 ...             ...           ...   
8262384  1.545489e+09  COBDPD3KxUR6kHRFd6   192.168.1.196         54034   
8262385  1.545489e+09  ClB8ai4Qrd9327GNH1   192.168.1.196         38638   
8262386  1.545487e+09   C7tILLtahZJ95prY2   192.168.1.196         41504   
8262387  1.545489e+09  CKyW4U3CKnNv9iyzV2   192.168.1.196           123   
8262388  1.545489e+09  CX5bG81XCH2suiPkO7  200.170.187.33             3   

           id.resp_haddr  id.resp_pport proto_enum service_string  \
0            192.168.1.1             53        udp            dns   
1            192.168.1.1             53        udp            dns   
2            192.168.1.1             53        udp            dns   
3         89.221.210.188            123        udp              -   
4            31.31.74.35            123        udp              -   
...                  ...            ...        ...            ...   
8262384  243.173.162.237             23        tcp              -   
8262385  115.129.182.143             23        tcp              -   
8262386  117.104.129.195             23        tcp              -   
8262387   89.221.210.188            123        udp              -   
8262388    192.168.1.196              1       icmp              -   

        duration_interval orig_bytes_count resp_bytes_count conn_state_string  \
0                5.005148               78                0                S0   
1                5.005145               78                0                S0   
2                5.005149               78                0                S0   
3                0.143648               48               48                SF   
4                0.004481               48               48                SF   
...                   ...              ...              ...               ...   
8262384                 -                -                -                S0   
8262385        144.578522                0                0                S2   
8262386        188.159685                0                0                S1   
8262387                 -                -                -                S0   
8262388                 -                -                -               OTH   

        local_orig_bool local_resp_bool  missed_bytes_count history_string  \
0                     -               -                   0              D   
1                     -               -                   0              D   
2                     -               -                   0              D   
3                     -               -                   0             Dd   
4                     -               -                   0             Dd   
...                 ...             ...                 ...            ...   
8262384               -               -                   0              S   
8262385               -               -                   0           ShAF   
8262386               -               -                   0           ShwA   
8262387               -               -                   0              D   
8262388               -               -                   0              -   

         orig_pkts_count  orig_ip_bytes_count  resp_pkts_count  resp_bytes  \
0                      2                  134                0           0   
1                      2                  134                0           0   
2                      2                  134                0           0   
3                      1                   76                1

In [30]:
print("Shape benigns",df_ben.shape)
print("shape ddos",df_ddos.shape)

Shape benigns (8262389, 23)
shape ddos (2185302, 23)


In [31]:
df_ben = df_ben.drop(['local_resp_bool', 'local_orig_bool','tunnel'], axis=1)
df_ddos = df_ddos.drop(['local_resp_bool', 'local_orig_bool','tunnel'], axis=1)

In [32]:
print("Shape benigns",df_ben.shape)
print("shape ddos",df_ddos.shape)

Shape benigns (8262389, 20)
shape ddos (2185302, 20)


In [33]:
# df_ben = df_ben[df_ben['proto_enum'].isin(['tcp', 'udp'])]
#filtering df_ben so that it only contains tcp and udp protocols

In [34]:
print("Shape benigns",df_ben.shape)
print("shape ddos",df_ddos.shape)

Shape benigns (8262389, 20)
shape ddos (2185302, 20)


In [35]:
# df_ben = df_ben[df_ben['service_string'].isin(['http','-'])]
#filtering df_ben so that it only contains http, -

In [36]:
print("Shape benigns",df_ben.shape)
print("shape ddos",df_ddos.shape)

Shape benigns (8262389, 20)
shape ddos (2185302, 20)


In [37]:
# df_ben = df_ben[df_ben['id.orig_addr'].isin(['192.168.1.196'])]
# filtering df_ben so that it only contains 192.168.1.196

In [38]:
print("Shape benigns",df_ben.shape)
print("shape ddos",df_ddos.shape)

Shape benigns (8262389, 20)
shape ddos (2185302, 20)


In [39]:
df_ben.columns.to_list()

['ts_time',
 'uid_string',
 'id.orig_addr',
 'id.orig_port',
 'id.resp_haddr',
 'id.resp_pport',
 'proto_enum',
 'service_string',
 'duration_interval',
 'orig_bytes_count',
 'resp_bytes_count',
 'conn_state_string',
 'missed_bytes_count',
 'history_string',
 'orig_pkts_count',
 'orig_ip_bytes_count',
 'resp_pkts_count',
 'resp_bytes',
 'Category',
 'Category-detail']

In [40]:
empty_count = df_ben['Category-detail'].apply(lambda x: str(x).strip() == "" or str(x).strip() == "-").sum()
print(empty_count)
#Shape benigns (8262389, 23)
#shape ddos (2185302, 23)


8262389


In [45]:
import numpy as np

# Clean the 'duration_interval' column
def clean_and_convert(value):
    # Check if the value is already numeric (float/int)
    if isinstance(value, (float, int)):
        return value

    # If value is a string, proceed with cleaning
    value = value.strip()
    if value.endswith('-'):
        value = value[:-1]
    if value == '--':
        return 0
    return pd.to_numeric(value, errors='coerce')

In [101]:
# Remove any columns that deem necessary
remove_cols = [
    'ts_time',
    'uid_string',
    'Category-detail',
    'orig_bytes_count',
    'resp_bytes_count'
]


for col in remove_cols:
    df_ben = df_ben.drop(columns=[col])
    df_ddos = df_ddos.drop(columns=[col])


X_ben = df_ben[:10000].drop(columns=['Category'])
X_ddos = df_ddos[:10000].drop(columns=['Category'])

X = pd.concat([X_ben, X_ddos], ignore_index=True)

# Combining the target labels
y_ben = df_ben[:10000]['Category']
y_ddos = df_ddos[:10000]['Category']

y = pd.concat([y_ben, y_ddos], ignore_index=True)
y, _ = pd.factorize(y)

# 5. Identify numerical and categorical columns
numerical_cols = [
    'id.orig_port',
    'id.resp_pport',
    'orig_bytes_count',
    'resp_bytes_count',
    'missed_bytes_count',
    'orig_pkts_count',
    'orig_ip_bytes_count',
    'resp_pkts_count',
    'resp_bytes',
]

categorical_cols = [
    'proto_enum',
    'service_string',
    'conn_state_string',
    'history_string',
    'id.orig_addr',
    'id.resp_haddr',
    'duration_interval',
]

# for col in numerical_cols:
#     X[col], _ = pd.to_numeric(col)
# df_ben['duration_interval'] = df_ben['duration_interval'].apply(clean_and_convert)
# df_ddos['duration_interval'] = df_ddos['duration_interval'].apply(clean_and_convert)

for col in categorical_cols:
    X[col], _ = pd.factorize(X[col])

X



20000
20000
2


In [ ]:
from sklearn.model_selection import StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import numpy as np

# Initialize the outer cross-validation
outer_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Define parameter grid for Random Forest hyperparameter tuning
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

# List to hold the accuracy scores from the outer CV loop
outer_scores = []

# Outer cross-validation loop
for train_idx, test_idx in outer_cv.split(X, y):
    X_train, X_test = X.values[train_idx], X.values[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    # Define inner cross-validation for hyperparameter tuning
    inner_cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

    # Initialize Random Forest model
    rf_model = RandomForestClassifier(random_state=42)

    # GridSearchCV for hyperparameter tuning within the inner CV loop
    grid_search = GridSearchCV(
        estimator=rf_model,
        param_grid=param_grid,
        cv=inner_cv,
        scoring='accuracy',
        n_jobs=-1
    )

    # Fit GridSearchCV on the training data of the current outer fold
    grid_search.fit(X_train, y_train)

    # Select the best model from the inner CV tuning
    best_model = grid_search.best_estimator_

    # Evaluate the best model on the outer fold test set
    y_pred = best_model.predict(X_test)
    outer_accuracy = accuracy_score(y_test, y_pred)
    outer_scores.append(outer_accuracy)

    print(f"Best hyperparameters for this fold: {grid_search.best_params_}")
    print(f"Accuracy for this fold: {outer_accuracy}")

# Calculate and print the final results from the outer cross-validation loop
print("\nCross-validated outer accuracy scores:", outer_scores)
print("Mean accuracy:", np.mean(outer_scores))
print("Standard deviation of accuracy:", np.std(outer_scores))

Best hyperparameters for this fold: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}
Accuracy for this fold: 1.0
[  0 123   3 123   0   1   5   1   0   1   1  76   1  76]
Best hyperparameters for this fold: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}
Accuracy for this fold: 1.0
[  0 123   3 123   0   1   5   1   0   1   1  76   1  76]
Best hyperparameters for this fold: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}
Accuracy for this fold: 1.0
[  0 123   3 123   0   1   5   1   0   1   1  76   1  76]
Best hyperparameters for this fold: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}
Accuracy for this fold: 0.99975
[  0 123   3 123   0   1   5   1   0   1   1  76   1  76]


KeyboardInterrupt: 